### ISSUE TITLE
Insight on SE5000H

### ISSUE THREAD

**Issue by AlexandreLogist** [jbuehl/solaredge#125]
Hi All,

Bought a SE5000H and wanted to implement the software on a rpi, as I also use this for all my energy meters trough my place talking by Modbus rs-485. But I'm having some questions...

- I tested the software, but never gets an answer back from my inverted. Is it needed that the server is set to rs-485 and will this impact data transmission to their 'cloud' monitoring servers?

- Anyone knows where to find the rs-232 port on this inverter?

I know it's not 100% related to the soft, but I would like to know why the inverter isn't responding to the commands :)

Kind regards,
Alex

**Comment by oliv3r** [comment]
Hey Alex,

You should be able to find the answer to most of your questions in other issues, but I'll give you some short answers so you can close the ticket :)

You can configure the device in a few 'server' modes; but only 1 can be active at the same time. You can have the 'cloud' server, e.g. tcp/ip e.g. the default where it reports online. You can use a Linux system to then to 'intercept' the traffic and forward, or just sniff using the tools in this repository.

If you want to use the RS-485 bus (or RS-232) you have to configure the device to be a rs-485 server or RS-232 server.  There are a few protocols supported by the SE5000H, sunspec, modbus and the SolarEdge propriatery protocol. The later is supported by semonitor, the others not. If you configure rs-485 or rs-232 you can't use the online reporting from the device itself. You may be able to still forward the data using semonitor; but not sure if this is supported yet.

The RS-232 is not soldered on all SE5000H's and some even miss the supporting circuitry (see another issue thread).

Hope this all helps, and happy reading; most of this is documented in the README
