### ISSUE TITLE
Does this work for new SetApp inverters? (e.g. SE6K)

### ISSUE THREAD

**Issue by maximevince** [jbuehl/solaredge#139]
Hi,

I had a SE6K installed recently, and have tunneled my ethernet connection via a Raspberry Pi where I capture the traffic.
It seems however, that I cannot find any encryption keys in the logs.
But I do see TLS traffic to the SolarEdge servers.

Does this method of passively logging still work on the recent "SetApp"/headless/noLCD inverters?

**Comment by AndyRPH** [comment]
If you have the newer models with Setapp,  consider this option: https://github.com/drobtravels/solaredge-local  It can pull the data via the local API without any encryption concerns.

**Comment by maximevince** [comment]
Thanks, this works!
