### ISSUE TITLE
Exception: timestamp out of range for platform time_t 

### ISSUE THREAD

**Issue by ocaj-nl** [jbuehl/solaredge#162]
Hi jbuehl (and others),

I've been running your code for about 5 years now without any issues. I take the output from semonitor.py and store it in a MySQL-database.
Suddenly 1 of my 2 inverters stopped reporting new date since 10 days. After a bit of searching I found that the code apparently stumbles on the reported data with an error "Exception: timestamp out of range for platform time_t ". Because this message is never confirmed to the inverter, this will always remain the next message to report, effectively blocking all further reports.
My other inverter keeps working, so it is not a generic issue.

I attached the debug-output of semonitor with all raw data.
[semonitor_exception.txt](https://github.com/jbuehl/solaredge/files/7049737/semonitor_exception.txt)

Do you have any suggestions how to fix this and make the flow of data continue?

I never updated to newer version of solaredge-master, so it is still running a mid-2016-version. As my inverters are non-connected, they still run the 2016-firmware. I never updated the raspberry pi this is running on either and therefore am still running python2.7. Seems like the current version of your software doesn't run on python2.7.
I'm a bit reluctant to updating to newer python as this raspberry pi is doing a few more data-gathering jobs in my home, so I'd rather not mess too much with it (it's fully isolated anyway, so my update-policy is "don't touch a working system")
On the other hand: I don't remember how much data is stored in the inverter, but I would like to fix it soon to prevent gaps in my long-term database.

**Comment by ethpi** [comment]
A few days ago I had exactly the same problem in a very similar setting.

Many thanks for this workaround. It works for me.

I use an version of semonitor.py from 2017 without any updates due to the same reasons as ocaj-nl. In my 2017-installation I couldn't find a file called data.py, but the file seData.py contains the function devDataDict().
