### ISSUE TITLE
Can we access module (optimizer) data totally remotely?

### ISSUE THREAD

**Issue by inckagan** [jbuehl/solaredge#163]
Hi everyone,

I would like to know if anyone tried to access optimizer data without connecting to inverter by using only SolarEdge Monitoring Platform credentials as a bot (such as using requests)?

Thanks in advance

**Comment by dragoshenron** [comment]
See https://github.com/dragoshenron/solaredge-webscrape

**Comment by inckagan** [comment]
Thanks for the response but the link seems broken, can you check again?

**Comment by dragoshenron** [comment]
The rep was set as private >.< Sorry.

**Comment by inckagan** [comment]
Thanks I am posting an issue about the error I got on that repo for the sake of convenience.
