### ISSUE TITLE
se2MQTT.py broken pipe

### ISSUE THREAD

**Issue by madether** [jbuehl/solaredge#17]
se2MQTT.py -c anon -u anon -p anon -s localhost -t /ha/value/solaredge /mnt/nfs/solar.json
[Errno 32] Broken pipe
[Errno 32] Broken pipe
[Errno 32] Broken pipe
[Errno 32] Broken pipe
[Errno 32] Broken pipe
[Errno 32] Broken pipe
[Errno 32] Broken pipe

**Comment by jbuehl** [comment]
The broken pipe message means that the program tried to write to a socket that was closed by the other side.  I would guess it has something to do with your MQTT server.  se2MQTT.py was written by @martynwendon so I don't know anything about it.

**Comment by madether** [comment]
local config issue.
