### ISSUE TITLE
Data no longer processed since 23/9/2017 12:00

### ISSUE THREAD

**Issue by vandalon** [jbuehl/solaredge#55]
Since noon today it seems messaged are no longer processed. I'm seeing the following:

Sep 23 15:29:37 /data/data/20170923152732.dat --> message: 1913 length: 551
Sep 23 15:29:37 dataLen:    0211
Sep 23 15:29:37 dataLenInv: fdee
Sep 23 15:29:37 sequence:   01c8
Sep 23 15:29:37 source:     731281f7
Sep 23 15:29:37 dest:       fffffffe
Sep 23 15:29:37 function:   003d
Sep 23 15:29:37 Decrypting message
Sep 23 15:29:37 dataLen:    839e
Sep 23 15:29:37 dataLenInv: 6db5
Sep 23 15:29:37 sequence:   e5d6
Sep 23 15:29:37 source:     2d538355
Sep 23 15:29:37 dest:       2af559a5
Sep 23 15:29:37 function:   e600
Sep 23 15:29:37 Data length is too big for the message
Sep 23 15:29:37 data:       9e 83 b5 6d d6 e5 55 83 53 2d a5 59 f5 2a 00 e6
Sep 23 15:29:37 data:       a7 ab 2f 7d 44 bf 48 ca ac 00 b6 dd 42 de d9 e2
Sep 23 15:29:37 data:       1d 05 31 37 da 0e a9 82 31 69 55 09 f3 9f f8 90
Sep 23 15:29:37 data:       24 92 cf 73 dc bf e3 0a ec 6a 7c bd dc f9 4b 46
Sep 23 15:29:37 data:       68 b7 70 9a f8 4a e8 ae 31 4a 08 c4 26 e6 ee 31
Sep 23 15:29:37 data:       cb f3 bb e1 7e 8f b0 4d 6f e4 63 e1 8a ea 80 66
Sep 23 15:29:37 data:       44 45 21 f3 bc c4 bc f4 59 a5 c3 d6 29 df 7a 8d
Sep 23 15:29:37 data:       e3 98 b3 da 06 a7 1d 59 22 42 08 81 e9 9a f8 4a
Sep 23 15:29:37 data:       f0 14 eb 59 5f 2f 20 14 74 e3 d7 45 4e a8 c6 fb
Sep 23 15:29:37 data:       55 c8 39 ba 06 92 f7 27 e3 d3 3a e6 08 fb e9 33
Sep 23 15:29:37 data:       ed a0 48 3d 43 16 2e 71 8f d9 3a 0b 79 b3 ba 72
Sep 23 15:29:37 data:       f9 45 3c 74 b2 05 98 75 47 6c 42 d8 6e be de 2b
Sep 23 15:29:37 data:       8e ec b8 e7 46 82 00 98 3e 34 fe 08 0f 5c 74 b7
Sep 23 15:29:37 data:       bc e1 59 5e 78 92 1a 56 1a ee 38 d7 59 24 60 53
Sep 23 15:29:37 data:       e6 03 79 9c af 5c 3b f6 9b 5c 86 e4 66 61 ae a2
Sep 23 15:29:37 data:       8e 97 6f a3 0c 17 2e 98 f4 b8 c8 0f 53 9b d4 ee
Sep 23 15:29:37 data:       11 a6 d9 92 7a 40 bf 52 7a b9 ac 0f ec 90 fe 18
Sep 23 15:29:37 data:       21 8e 78 79 88 53 34 be 62 ab 31 21 2c 3b 20 e1
Sep 23 15:29:37 data:       c8 05 b2 83 e9 15 92 ff 65 f8 8b 01 e6 7c ff 8c
Sep 23 15:29:37 data:       ff 35 92 f9 54 78 a5 dd 5a 85 d2 39 eb 24 f2 6d
Sep 23 15:29:37 data:       30 e1 a4 35 e8 53 c8 7b f8 b8 4b 4c 62 2d cc a3
Sep 23 15:29:37 data:       17 ba 1f 15 70 50 ae 10 13 f2 f3 3b de 6b cf 90
Sep 23 15:29:37 data:       38 fd 90 36 f8 4e a6 04 0b c9 7c f0 3b 24 e0 23
Sep 23 15:29:37 data:       c9 59 af 10 d0 ad 07 7e 0e 0f 6b 68 8c 1c cc 03
Sep 23 15:29:37 data:       7d fb 89 a0 38 44 92 3d 4b bd 80 1f d5 a3 4d f5
Sep 23 15:29:37 data:       fe 64 70 ed 64 2e fb f1 e1 5c f9 49 21 12 41 a7
Sep 23 15:29:37 data:       ba 9a ed 53 58 c7 7d 21 e9 f4 f4 84 c6 84 b0 6b
Sep 23 15:29:37 data:       9c fb dc f3 72 e8 e6 75 64 32 a2 59 2d 0e 41 b4
Sep 23 15:29:37 data:       17 f7 7f e1 d9 df 00 a9 4d 2f b4 0d 3d 0f 00 a3
Sep 23 15:29:37 data:       c6 c4 54 23 ac 0a 2d d7 b3 2d 3c b6 ec 8f fe b8
Sep 23 15:29:37 data:       65 07 62 05 55 de 97 d7 4b a1 ad 57 76 68 c0 09
Sep 23 15:29:37 data:       1c 56 f9 8a 3f 02 24
Sep 23 15:29:37 Ignoring this message
Sep 23 15:29:37

**Comment by oliv3r** [comment]
your data is encrypted, did you store the encryption key previously?
Read the readme about how to extract the key from your inverter.
